### ISSUE TITLE
Forest road Designer plugin not working after updating to QGIS 3.32 Lima

### ISSUE THREAD

**Issue by Xadamo** [GobiernoLaRioja/forestroaddesigner#7]
After upgrading to latest version of QGIS this plugin is giving errors upon installation and cannot be used. 

See error log below: 

Couldn't load plugin 'forestroaddesigner' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'frd_utils' 
Traceback (most recent call last):
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\optimizer_qgis.py", line 47, in 
    from .route_optimizer import a_star
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\route_optimizer\a_star.py", line 19, in 
    import scipy.interpolate
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\scipy\interpolate\__init__.py", line 167, in 
    from ._interpolate import *
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\scipy\interpolate\_interpolate.py", line 8, in 
    import scipy.special as spec
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\scipy\special\__init__.py", line 689, in 
    from . import add_newdocs, basic, orthogonal, specfun, sf_error, spfun_stats
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: DLL load failed while importing specfun: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\__init__.py", line 34, in classFactory
    from .forest_road_designer import ForestRoadDesigner
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\forest_road_designer.py", line 31, in 
    from .processing_provider.provider import Provider
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\processing_provider\provider.py", line 4, in 
    from .frd_processing_algorithm import ForestRoadDesignerProcessingAlgorithm
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\processing_provider\frd_processing_algorithm.py", line 33, in 
    from .. import optimizer_qgis as oq
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\forestroaddesigner\optimizer_qgis.py", line 51, in 
    import frd_utils
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'frd_utils'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.2-Lima Lima, c0b88339 

Python Path:
C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\road_slope_calculator
C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenTopography-DEM-Downloader
C:/OSGeo4W/apps/qgis/./python
C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis/./python/plugins
C:\OSGeo4W\apps\grass\grass83\etc\python
C:\Users\....\Documents
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\Users\....\AppData\Roaming\Python\Python39\site-packages
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/..../AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\....\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by David-Gonzalez-Panoimagen** [comment]
It seems to be a problem with scipy library. 
I tried to reproduce the error installing QGIS 3.32 with OSGeo4W installer but works with no issues. The standalone installation also works correctly.
Try to import scipy from Python console in QGIS. If throws an error, try to install spicy library. Otherwise you can get scipy version installed (scipy.__version__) . QGIS 3.32 is running with scipy 1.6.2 version.

**Comment by Xadamo** [comment]
I am still not able to make the plugin work actually. I used it with much satisfaction in the past.

**Comment by Xadamo** [comment]
Hola David,

I have tried everything, reinstalling QGIS, downgrading to older version, upgrading to 3.34, but the problems is still there.
I dont kno how to operate the python conmsole to install scipy and spicy as you suggest.. Could you provide instructions?

**Comment by Xadamo** [comment]
Completely uninstalling everything with OSGEO4 and manually deleting everything related to QGIS, plugins and Python solved the issue finally. 

I am using the plugin currently a lot and in general I am very happy with it. However, it does seem to make QGIS crash quite regularly. When working with it intensely, I need to constantly save my work as QGIS is crashing about every 30-60 minutes.

Is anyone else expereincing this?

**Comment by Xadamo** [comment]
## User Feedback
The crash typically happens when I start editing features, right after I switched from the interactive road design mode of the plugin to the normal feature editing mode in QGIS.

Typical QGIS Crash report while saving newly created feature with forest road designer plugin:



## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006bb4 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QHashData::free_helper :
QHeaderView::logicalIndexAt :
QHeaderView::logicalIndexAt :
QObject::qt_static_metacall :
QObject::destroyed :
QWidget::~QWidget :
QAbstractScrollAreaPrivate::~QAbstractScrollAreaPrivate :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsScrollArea::QgsScrollArea :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterHistogramWidget::QgsRasterHistogramWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMapLayerConfigWidgetFactory::operator= :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAttributeTableDialog::~QgsAttributeTableDialog :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAttributeTableDialog::~QgsAttributeTableDialog :
QObject::event :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.34.1-Prizren
QGIS code revision: 133927424d
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.1
Running against GDAL: 3.8.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by pmperez-larioja** [comment]
Closed due to inactivity
